name: 'Terraform Apply Workflow'

on:
  workflow_dispatch:
    inputs:
      working_directory:
        description: 'Terraform working directory to apply'
        required: true
        type: string

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: 'us-west-2'

jobs:
  terraform_apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{ inputs.working_directory }}

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: ${{ inputs.working_directory }}