name: 'Terraform Dynamic Menu'

on:
  workflow_dispatch:

jobs:
  scan_terraform_dirs:
    name: 'Scan Terraform Directories'
    runs-on: ubuntu-latest
    outputs:
      terraform_dirs: ${{ steps.find-tf-dirs.outputs.directories }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Find Terraform Directories
        id: find-tf-dirs
        run: |
          # Find all directories containing .tf files
          DIRS=$(find . -name "*.tf" | xargs -I{} dirname {} | sort -u | jq -R -s 'split("\n") | map(select(length > 0))')
          echo "directories=$DIRS" >> $GITHUB_OUTPUT
          echo "Found Terraform directories: $DIRS"

  create_menu:
    name: 'Present Directory Menu'
    needs: scan_terraform_dirs
    runs-on: ubuntu-latest
    
    steps:
      - name: Create Dynamic Menu
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const dirs = JSON.parse('${{ needs.scan_terraform_dirs.outputs.terraform_dirs }}');
            
            if (dirs.length === 0) {
              core.setFailed('No Terraform directories found in the repository');
              return;
            }
            
            // Create a workflow dispatch menu for each directory
            const workflowId = 'terraform-manual.yml';
            
            // Display a menu with the directories
            console.log('Available Terraform directories:');
            dirs.forEach((dir, index) => {
              console.log(`${index + 1}. ${dir}`);
            });
            
            console.log('\nPlease manually trigger the terraform-manual workflow with your selected directory.');
