name: 'Terraform Cross-Branch Workflow'

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select branch to checkout'
        required: true
        default: 'master'
      target_directory:
        description: 'Select Terraform directory (auto-updated)'
        required: true
        type: choice
        options:
          - terraform/ec2
        default: 'terraform/ec2'
      action:
        description: 'Terraform action to perform'
        required: true
        type: choice
        options:
          - plan
          - apply
        default: 'plan'

permissions:
  contents: read
  pull-requests: write
  id-token: write

env:
  AWS_REGION: 'us-west-2'

jobs:
  # Dynamically fetch Terraform directories from selected branch
  fetch_terraform_dirs:
    name: 'Fetch Terraform Directories'
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.get-dirs.outputs.directories }}
      
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || 'master' }}
          fetch-depth: 0
      
      - name: Find Terraform Directories
        id: get-dirs
        run: |
          echo "查找分支 '${{ github.event.inputs.branch || 'master' }}' 上的Terraform目录..."
          
          # 查找所有包含.tf文件的目录
          DIRS=$(find . -name "*.tf" | xargs -I{} dirname {} | sort -u | sed 's|^\./||' | grep -v '^\.git' | jq -R -s 'split("\n") | map(select(length > 0))')
          
          # 处理为正确的GitHub Actions输出格式
          DIRS_FORMATTED=$(echo $DIRS | jq -c .)
          echo "directories=$DIRS_FORMATTED" >> $GITHUB_OUTPUT
          
          echo "找到的Terraform目录: $DIRS"
  
  # 主要的Terraform作业
  terraform_job:
    name: 'Terraform操作'
    needs: fetch_terraform_dirs
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || 'master' }}
      
      - name: 设置Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.0.0'
      
      - name: 配置AWS凭证
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: 显示所选目录
        run: |
          echo "分支: ${{ github.event.inputs.branch }}"
          echo "所选Terraform目录: ${{ github.event.inputs.target_directory }}"
          echo "操作: ${{ github.event.inputs.action }}"
          echo "可用目录: ${{ needs.fetch_terraform_dirs.outputs.directories }}"
      
      - name: Terraform初始化
        run: |
          cd ${{ github.event.inputs.target_directory }}
          terraform init
      
      - name: Terraform计划
        run: |
          cd ${{ github.event.inputs.target_directory }}
          terraform plan
        if: github.event.inputs.action == 'plan'
      
      - name: Terraform应用
        run: |
          cd ${{ github.event.inputs.target_directory }}
          terraform apply -auto-approve
        if: github.event.inputs.action == 'apply'
